DROP TABLE IF EXISTS questions CASCADE;

CREATE TABLE questions (
question_id SERIAL PRIMARY KEY,
survey_id INTEGER REFERENCES surveys ON UPDATE CASCADE ON DELETE CASCADE,
question TEXT,
style_id INTEGER

);