/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feedy.view;

/**
 *
 * @author Sebastian
 */
public class SurveyItem extends javax.swing.JPanel {

    /**
     * Creates new form SurveyItem
     */
    public SurveyItem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        boarderContainer = new javax.swing.JPanel();
        buttonContainer = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        labelContainer = new javax.swing.JPanel();
        surveyTypeLabel = new javax.swing.JLabel();
        placeLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        counterLabel = new javax.swing.JLabel();

        boarderContainer.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonContainer.setLayout(new java.awt.GridLayout(1, 0));

        jButton3.setText("Auswertung");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        buttonContainer.add(jButton3);

        jButton4.setText("Löschen");
        buttonContainer.add(jButton4);

        labelContainer.setLayout(new java.awt.GridLayout(1, 0));

        surveyTypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        surveyTypeLabel.setText("Seminartyp");
        labelContainer.add(surveyTypeLabel);

        placeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        placeLabel.setText("Ort");
        labelContainer.add(placeLabel);

        dateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateLabel.setText("Datum");
        labelContainer.add(dateLabel);

        counterLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        counterLabel.setText("Anzahl ");
        labelContainer.add(counterLabel);

        javax.swing.GroupLayout boarderContainerLayout = new javax.swing.GroupLayout(boarderContainer);
        boarderContainer.setLayout(boarderContainerLayout);
        boarderContainerLayout.setHorizontalGroup(
            boarderContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, boarderContainerLayout.createSequentialGroup()
                .addComponent(labelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        boarderContainerLayout.setVerticalGroup(
            boarderContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(boarderContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(boarderContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boarderContainer;
    private javax.swing.JPanel buttonContainer;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel counterLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel labelContainer;
    private javax.swing.JLabel placeLabel;
    private javax.swing.JLabel surveyTypeLabel;
    // End of variables declaration//GEN-END:variables
}
