/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feedy.view;

import feedy.Controller.Controller;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.accessibility.AccessibleRelation;

/**
 *
 * @author Sebastian
 */
public class WelcomeView extends BasePanel {

    /**
     * Creates new form welcomePane
     * @param cntrl
     */
    public WelcomeView(Controller cntrl) {
        controller = cntrl;
        initComponents();
        
        
        newSurveyBtn.addActionListener(controller.getActionListenerAddSurveyBtn());
    };

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        newSurveyBtn = new javax.swing.JButton();
        toDatabaseBtn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Wilkommen!");

        newSurveyBtn.setText("neue Umfrage");
        newSurveyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSurveyBtnActionPerformed(evt);
            }
        });

        toDatabaseBtn.setText("zur Datenbank");
        toDatabaseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toDatabaseBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                    .addComponent(newSurveyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(toDatabaseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(newSurveyBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toDatabaseBtn)
                .addContainerGap(179, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void newSurveyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSurveyBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newSurveyBtnActionPerformed

    private void toDatabaseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toDatabaseBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toDatabaseBtnActionPerformed
    
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton newSurveyBtn;
    private javax.swing.JButton toDatabaseBtn;
    // End of variables declaration//GEN-END:variables
    private Controller controller; 

    
}
