/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feedy.Controller;

import feedy.view.AddSurveyView;
import feedy.view.Substitute;


import feedy.view.MainWindow;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author ratz
 */
public class Controller {

    public Controller(){
    };
        public ActionListener getActionListenerAddSurveyBtn() {
        ActionListener listener = new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                mainWindow.setPanel(new AddSurveyView());
            }
        };
        
        return listener;
    }

    public void setMainWindow(MainWindow mainWindow) {
        this.mainWindow = mainWindow;
    }

    private MainWindow mainWindow;

    /** ----------------- AUTOGENERATED---------------- **/

        
   
       
    
        
        
    }

    
    

    


